### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by qingchenkanlu** [edwardnguyen1705/robotic-grasping-cornell#2]
Hi,I have find some problems in your profile robotic-grasping-faster-rcnn-pytorch-1.0, but there can't write issue. the structure of vgg16 maybe need to be changed,the source file 
class vgg16(_fasterRCNN):
  def __init__(self, classes, pretrained=False, class_agnostic=False):
    self.model_path = 'data/pretrained_model/vgg16_caffe.pth'
    self.dout_base_model = 512
    self.pretrained = pretrained
    self.class_agnostic = class_agnostic
but yours in predict.py
  self.fasterRCNN = vgg16(self.grasp_classes,
                                self.grasp_poses,
                                pretrained=False,
                                class_agnostic=self.class_agnostic,)
is there any mistake?

**Comment by edwardnguyen1705** [comment]
I have change the setting, now you can  raise issues in that project. Then I will answer.
