### ISSUE TITLE
Link failed

### ISSUE THREAD

**Issue by SHYang1210** [edwardnguyen1705/robotic-grasping-cornell#3]
hi，The GoogleDrive link you provided is failed. Can you provide it again?

**Comment by edwardnguyen1705** [comment]
@SHYang1210 
hi, please check again.

**Comment by SHYang1210** [comment]
OK，it is work，thank you。

**Comment by KomputerMaster64** [comment]
> [@SHYang1210](https://github.com/SHYang1210) hi, please check again.

Hello

I am not able to access the pre-trained model weights via the google drive link:
Download the pretrained model [GoogleDrive](https://drive.google.com/drive/folders/1Th4hMEdSr3kTQBXJTIDstSJn2eUWvoaa?usp=sharing)

<img width="1792" alt="Image" src="https://github.com/user-attachments/assets/5eba477b-42f1-40c7-a06a-b7a6e2e2a400" />

I also found an alternate in assets but I am not sure if it is referring to the same weights:
[Attached pre-trained weights for GG-CNN on the Cornell Grasping Dataset using depth data only](https://github.com/dougsm/ggcnn/releases/tag/v0.1) - https://github.com/dougsm/ggcnn/releases/tag/v0.1

<img width="1792" alt="Image" src="https://github.com/user-attachments/assets/ba8aab44-c1f4-4ad7-88f5-1f16fe96c247" />

**Comment by edwardnguyen1705** [comment]
Hi @KomputerMaster64 ,
At some point, my GD was full, and I had to delete the model. Please git clone and train yourself.
